language: elixir
elixir:
- 1.1.1
otp_release:
- 18.1
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database mikeworks_test;' -U postgres
deploy:
  provider: heroku
  app: mikeworks-api
  api_key:
    secure: E/fcKyCGsbuFPgBkfyDY0myMlXS6riJrGH8BVV1aAhoKMfXO+wPxLxGs2oAgSW7vwueK9HTIy6L9QMZeBFNNPXJiX1W89LPGaDxmw+VzHd9apvDXWjiVUADQUYYAmp865PkZBA2gYS0+TRUY8iUnNburqhrlOOuvYHU0aWw9UyANabw+yrMP36N2soeMxKgEudCoKq8Am18YpXIhutCJv6KuRUsg/jnkBcV8qyZF0GbgLWfUOTKhQF6/bOAAMhU7u0+egbxJcurG78tj5eiYN1pFbFWwN9p6/PXiammCDMnrBjBLqrkR9tlw+iV18mSdZDJL+adhBsfMOh66X75eNI0AShHAmp00sPrFLYQ7FnDhlaslz+GWS3u6ti73V0veg7YDNYJkFTvVYCT1qjrG3AxOIj3X0D+sjoGkWNwUDM7oU+2RxTXnkZB92T0jT17P9Eti3ykDSOkRlCV+U3W73Hn4rEmHjL81U+wJusJs/FhBa4CZQtvE/SztwxfeXNL0zYxZ2sJPNIbI+YGzazKOmxvI6ZIqhq+/7uG2FYVWmN7KSgpPjNaR854OVXe1srN85AZChuvQBZwT76WGzZ8VmRUh5Ite08tn1Mh0/W7YghQtDmYejnmSrzdvyUgmEMdr7edjwK2+thcsICJ4Kk3Ijzj3zNJ4S+/FxN0h/+OoKOM=
notifications:
  email:
  - michael.l.north@gmail.com
